FROM apache/airflow:3.3.2

USER root

RUN apt-get update && apt-get install -y gcc && apt-get clean

USER airflow 

COPY requirements.txt .

RUN pip install --no-cache-dir "apache-airflow==3.3.2" \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.3.2/constraints-3.13.txt" \
    && pip install --no-cache-dir -r requirements.txt