sources:
  - name: walmart_databricks
    database: walmart_project
    schema: bronze
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: order_items
      - name: stores
      - name: employees